# Generated by Django 3.1.14 on 2023-08-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Название')),
                ('title_en', models.TextField(blank=True, verbose_name='Название на английском')),
                ('title_jp', models.TextField(blank=True, verbose_name='Название на японском')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(null=True, upload_to='pokemons')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(blank=True, verbose_name='Появляется')),
                ('disappeared_at', models.DateTimeField(blank=True, verbose_name='Пропадает')),
                ('level', models.IntegerField(blank=True, verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, verbose_name='Здоровье')),
                ('attack', models.IntegerField(blank=True, verbose_name='Атака')),
                ('defence', models.IntegerField(blank=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
