# Generated by Django 3.1.14 on 2023-08-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
